# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YCno4ZmmpwkDyiaFti4oSA8ibHbrQhZgMKcO4TBx3+xIRoJTmuz8lt+bZsIQQ/8umhHhOpywr1bIIvtZ53xlKeHWrVE1XVaJDW/Iad3p0o239NncaJfjpWoODBWTENpcBE1i/E34ETu26D0G+csE8C7LrDB9O1DAP3dFBkVHAvvLd+vCJUPh8mahcanSGMkzUScD4RmgRrg4wJvBSwgP952MLWiQMv3lTmWnFwDyY0GP4IqNEz/tliK7lZmEBITJEeP73RJpF5u0PdllORNhpESmws88PZxuF0pD2pKdIxw+g8+xA5AM9LFo877qn88tiMxeCBLSgKnPOhRo/VeVTB/QlWNPh0oPVvx2/IwKkqCiAUHqPEpvGnHOORxi1W/gOBY4Ca1Nqq5ykCbL9n1raTuXgnOaiGwgdzvIkp4Omh0zB+DBYeOxqlfDk9+VOM/R1ZWGErK8WSARflnR7X86amRbwouAVaN9H2SEsXJYu/5W3hsflKQO56sz3+2sa9bYEU9VNOrkmsTHVNGGZd7hTdt/IlO6ovPVkBc4IZ9aThzxbCLBZGDkll3a1boqcinQVDM8KgilA4nMcel3ks31bBD9C93BWoZYsLE4907kKmaCzsbO2/Hb5rAqQ0KTQ4ydNq0gaAS4ZuLvUe8Iq80Vy88KZsi9x+/Fx59ZiWo64xs="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
