travis:
  secure:
    BINSTAR_TOKEN: aMqmGb7uOrqlIy37I8eELn/6GIIq4v2g8tS85N4VG5whcZNS4OvX8VnikccCdLSVs2f2u8aAD+KCuILCTfX1hRVHpgt6wsj+RU4vvHLno99KaLM91ilr2MVZTa9jirHS5utu4slfhw7CczA2vI9d7RaHvVHVHC1xoYbSu+OQ7/kiZz7Q6kCiCzdHXDLg+gwOBR4nD0eBb9gNHcoGe50CFOogv3c7Pn14xf/eNq8L64MqaYDDYyhOsjhjHfypICTRMovp2n61Y6uesxXCJXyBXtDt/qxLaSjvuLAaQsAKtahjCl6mz11sGjfdAOoRHTxM06ua7VUIsn91FBU/0aPSqqivr3+DreKpteNr45CUbXWJO/5Ijcg67+yQZnUY7qcCcWfIIwpPRlsqoqk26qJsIhPgZIzrIfjbI5yA7vUjDsIVm1c62QrIctBgEFifW1UOIAiYVjIKmn1OqhaSIhfcFP+vsoSv+ZRopEJ5rjdFLB48CLrFkW4+jbD2w/GEa+/dfFYMsq/9Cw4X0VTPwSakQvQlNMWpgD1W7yo5VByFCkLU3zcX7jmcG0rtf+aakFdsjdV3zvwM8vRBxOOwKVrgxbqKZy3FxQurka14Zk0g8gROvH1oeZTQQ03z1y5bvXqqaGqBFnsDpwJHdzjKtBr0ahJsvVMYvhOIkgpGrmYQoj0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
